In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas

web scraping = extracting data from websites

target website: https://www.football-data.co.uk/data.php

In [4]:
# reading one csv file from the website 
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [5]:
# showing data frame
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

# Read .csv from multiple URLs with Pandas

https://www.football-data.co.uk/mmz4281/2526/E0.csv
link = root + season + link

"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

https://www.football-data.co.uk/mmz4281/2526/E0.csv
https://www.football-data.co.uk/mmz4281/2526/E1.csv
https://www.football-data.co.uk/mmz4281/2526/E2.csv
https://www.football-data.co.uk/mmz4281/2526/E3.csv
https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [8]:
# creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)

In [7]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

In [8]:
# creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)

In [9]:
# length of frames
len(frames)

5

In [11]:
# show first, second, and third elements
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

# Multiple Seasons

In [8]:
# creating list of seasons
seasons = ['2526', '2425', '2324', '2223, '2122']
frames = []

# looping through leagues, read multiple csv and append it into a list
for seasons in range(21, 25):
    df = pd.read_csv(root + seasons + '/' + 'E0' + '.csv')
    frames.append(df)

In [16]:
for season in range(19, 25) :
    print(str(season) + str(season+1))

1920
2021
2122
2223
2324
2425

In [21]:
# creating list of leagues
leagues = ['E0', 'E2', 'E3']
frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(19, 25):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)
frames

[    Div  season        Date   Time        HomeTeam          AwayTeam  FTHG  \
 0    E0      19  09/08/2019  20:00       Liverpool           Norwich     4
 1    E0      19  10/08/2019  12:30        West Ham          Man City     0
 2    E0      19  10/08/2019  15:00     Bournemouth  Sheffield United     1
 3    E0      19  10/08/2019  15:00         Burnley       Southampton     3
 4    E0      19  10/08/2019  15:00  Crystal Palace           Everton     0
 ..   ..     ...         ...    ...             ...               ...   ...
 375  E0      19  26/07/2020  16:00       Leicester        Man United     0
 376  E0      19  26/07/2020  16:00        Man City           Norwich     5
 377  E0      19  26/07/2020  16:00       Newcastle         Liverpool     1
 378  E0      19  26/07/2020  16:00     Southampton  Sheffield United     3
 379  E0      19  26/07/2020  16:00        West Ham       Aston Villa     1

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       1   H     4  ...      3.43 -2.25     1.91      1.99   1.94   1.98
 1       5   A     0  ...      2.91  1.75     1.95      1.95   1.96   1.97
 2       1   D     0  ...      1.92 -0.50     1.95      1.95   1.98   1.95
 3       0   H     0  ...      1.71  0.00     1.87      2.03   1.89   2.03
 4       0   D     0  ...      1.71  0.25     1.82      2.08   1.97   1.96
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     2   A     0  ...      2.03  0.50     1.89      2.01   1.88   2.05
 376     0   H     2  ...      5.77 -3.75     2.03      1.87   2.01   1.88
 377     3   A     1  ...      2.40  1.00     1.94      1.96   1.95   1.97
 378     1   H     0  ...      2.01 -0.50     1.97      1.93   2.00   1.93
 379     1   D     0  ...      2.03  0.00     1.93      1.97   1.95   1.98

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       1.99     2.07     1.90     1.99
 1       2.07     1.98     1.97     1.92
 2       2.00     1.96     1.96     1.92
 3       1.90     2.07     1.86     2.02
 4       2.03     2.08     1.96     1.93
 ..       ...      ...      ...      ...
 375     1.94     2.05     1.86     2.02
 376     2.06     1.88     2.02     1.84
 377     2.03     2.00     1.95     1.92
 378     2.03     1.96     1.98     1.89
 379     1.99     2.00     1.93     1.95

 [380 rows x 107 columns],
     Div  season        Date   Time          HomeTeam        AwayTeam  FTHG  \
 0    E0      20  12/09/2020  12:30            Fulham         Arsenal     0
 1    E0      20  12/09/2020  15:00    Crystal Palace     Southampton     1
 2    E0      20  12/09/2020  17:30         Liverpool           Leeds     4
 3    E0      20  12/09/2020  20:00          West Ham       Newcastle     0
 4    E0      20  13/09/2020  14:00         West Brom       Leicester     0
 ..   ..     ...         ...    ...               ...             ...   ...
 375  E0      20  23/05/2021  16:00         Liverpool  Crystal Palace     2
 376  E0      20  23/05/2021  16:00          Man City         Everton     5
 377  E0      20  23/05/2021  16:00  Sheffield United         Burnley     1
 378  E0      20  23/05/2021  16:00          West Ham     Southampton     3
 379  E0      20  23/05/2021  16:00            Wolves      Man United     1

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       3   A     0  ...      1.84  0.75     2.01      1.89   2.02   1.91
 1       0   H     1  ...      1.70  0.25     1.78      2.13   1.79   2.17
 2       3   H     3  ...      2.62 -1.50     1.85      2.05   1.85   2.08
 3       2   A     0  ...      1.92 -0.50     2.03      1.87   2.04   1.88
 4       3   A     0  ...      1.73  0.25     1.92      1.98   1.93   1.99
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     0   H     1  ...      3.49 -2.25     1.86      2.04   1.88   2.03
 376     0   H     2  ...      2.77 -1.75     2.01      1.89   1.99   1.89
 377     0   H     1  ...      2.05  0.00     2.04      1.86   2.05   1.86
 378     0   H     2  ...      2.14 -0.75     2.00      1.90   2.02   1.91
 379     2   A     1  ...      1.62 -0.25     2.04      1.86   2.10   1.84

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.13     1.92     2.02     1.87
 1       1.85     2.18     1.79     2.12
 2       1.90     2.16     1.84     2.04
 3       2.09     1.91     2.02     1.86
 4       1.95     2.01     1.91     1.97
 ..       ...      ...      ...      ...
 375     1.98     2.14     1.88     2.00
 376     2.20     2.00     2.03     1.85
 377     2.17     1.90     2.03     1.84
 378     2.06     2.01     1.99     1.89
 379     2.10     1.94     2.00     1.88

 [380 rows x 107 columns],
     Div  season        Date   Time        HomeTeam        AwayTeam  FTHG  \
 0    E0      21  13/08/2021  20:00       Brentford         Arsenal     2
 1    E0      21  14/08/2021  12:30      Man United           Leeds     5
 2    E0      21  14/08/2021  15:00         Burnley        Brighton     1
 3    E0      21  14/08/2021  15:00         Chelsea  Crystal Palace     3
 4    E0      21  14/08/2021  15:00         Everton     Southampton     3
 ..   ..     ...         ...    ...             ...             ...   ...
 375  E0      21  22/05/2022  16:00  Crystal Palace      Man United     1
 376  E0      21  22/05/2022  16:00       Leicester     Southampton     4
 377  E0      21  22/05/2022  16:00       Liverpool          Wolves     3
 378  E0      21  22/05/2022  16:00        Man City     Aston Villa     3
 379  E0      21  22/05/2022  16:00         Norwich       Tottenham     0

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       0   H     1  ...      1.62  0.50     1.75      2.05   1.81   2.13
 1       1   H     1  ...      2.25 -1.00     2.05      1.75   2.17   1.77
 2       2   A     1  ...      1.62  0.25     1.79      2.15   1.81   2.14
 3       0   H     2  ...      1.94 -1.50     2.05      1.75   2.12   1.81
 4       1   H     0  ...      1.67 -0.50     2.05      1.88   2.05   1.88
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     0   H     1  ...      2.04  0.25     1.68      2.15   1.74   2.23
 376     1   H     0  ...      2.63 -0.75     1.83      2.07   1.88   2.03
 377     1   H     1  ...      3.28 -2.50     2.02      1.77   2.06   1.83
 378     2   H     0  ...      3.36 -2.25     2.06      1.84   2.05   1.86
 379     5   A     0  ...      2.40  1.50     1.95      1.95   1.96   1.94

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0       2.05     2.17     1.80     2.09
 1       2.19     1.93     2.10     1.79
 2       1.82     2.19     1.79     2.12
 3       2.16     1.93     2.06     1.82
 4       2.08     1.90     2.03     1.86
 ..       ...      ...      ...      ...
 375     1.88     2.25     1.74     2.16
 376     1.94     2.26     1.87     2.01
 377     2.19     1.99     2.07     1.80
 378     2.09     2.03     2.01     1.87
 379     2.16     1.98     1.99     1.89

 [380 rows x 107 columns],
     Div  season        Date   Time        HomeTeam       AwayTeam  FTHG  FTAG  \
 0    E0      22  05/08/2022  20:00  Crystal Palace        Arsenal     0     2
 1    E0      22  06/08/2022  12:30          Fulham      Liverpool     2     2
 2    E0      22  06/08/2022  15:00     Bournemouth    Aston Villa     2     0
 3    E0      22  06/08/2022  15:00           Leeds         Wolves     2     1
 4    E0      22  06/08/2022  15:00       Newcastle  Nott'm Forest     2     0
 ..   ..     ...         ...    ...             ...            ...   ...   ...
 375  E0      22  28/05/2023  16:30         Everton    Bournemouth     1     0
 376  E0      22  28/05/2023  16:30           Leeds      Tottenham     1     4
 377  E0      22  28/05/2023  16:30       Leicester       West Ham     2     1
 378  E0      22  28/05/2023  16:30      Man United         Fulham     2     1
 379  E0      22  28/05/2023  16:30     Southampton      Liverpool     4     4

     FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
 0     A     0  ...      1.76  0.50     2.09      1.84   2.04   1.88     2.09
 1     D     1  ...      2.73  1.75     1.90      2.03   1.91   2.02     2.01
 2     H     1  ...      1.76  0.50     1.93      2.00   1.93   2.00     1.94
 3     H     1  ...      1.87 -0.25     2.08      1.85   2.10   1.84     2.14
 4     H     0  ...      1.89 -1.00     1.97      1.96   1.99   1.93     2.19
 ..   ..   ...  ...       ...   ...      ...       ...    ...    ...      ...
 375   H     0  ...      2.14 -1.00     2.02      1.77   2.10   1.81     2.17
 376   A     0  ...      2.50  0.25     1.84      2.06   1.83   2.10     1.90
 377   H     1  ...      2.51 -0.25     1.75      2.05   1.85   2.06     1.90
 378   H     1  ...      2.95 -1.25     1.98      1.92   1.98   1.93     2.07
 379   D     2  ...      3.22  1.25     1.82      2.08   1.85   2.07     1.96

      MaxCAHA  AvgCAHH  AvgCAHA
 0       1.88     2.03     1.85
 1       2.06     1.89     1.99
 2       2.04     1.88     2.00
 3       1.87     2.08     1.81
 4       1.97     2.03     1.86
 ..       ...      ...      ...
 375     1.92     2.03     1.83
 376     2.14     1.81     2.06
 377     2.16     1.82     2.04
 378     1.98     1.97     1.89
 379     2.12     1.88     1.98

 [380 rows x 107 columns],
     Div  season        Date   Time          HomeTeam       AwayTeam  FTHG  \
 0    E0      23  11/08/2023  20:00           Burnley       Man City     0
 1    E0      23  12/08/2023  12:30           Arsenal  Nott'm Forest     2
 2    E0      23  12/08/2023  15:00       Bournemouth       West Ham     1
 3    E0      23  12/08/2023  15:00          Brighton          Luton     4
 4    E0      23  12/08/2023  15:00           Everton         Fulham     0
 ..   ..     ...         ...    ...               ...            ...   ...
 375  E0      23  19/05/2024  16:00    Crystal Palace    Aston Villa     5
 376  E0      23  19/05/2024  16:00         Liverpool         Wolves     2
 377  E0      23  19/05/2024  16:00             Luton         Fulham     2
 378  E0      23  19/05/2024  16:00          Man City       West Ham     3
 379  E0      23  19/05/2024  16:00  Sheffield United      Tottenham     0

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       3   A     0  ...      2.28  1.50     1.95      1.98   1.95   1.97
 1       1   H     2  ...      2.63 -2.00     1.95      1.98   1.93   1.97
 2       1   D     0  ...      2.12  0.00     2.02      1.91   2.01   1.92
 3       1   H     1  ...      2.48 -1.75     2.01      1.92   2.00   1.91
 4       1   A     0  ...      1.71 -0.25     2.06      1.87   2.04   1.88
 ..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
 375     0   H     2  ...      2.78 -0.75     1.73      2.08   1.78   2.16
 376     0   H     2  ...      5.17 -2.75     2.07      1.86   2.04   1.85
 377     4   A     1  ...      2.69  0.25     2.00      1.93   1.99   1.93
 378     1   H     2  ...      4.82 -3.00     2.03      1.90   1.99   1.90
 379     3   A     0  ...      3.81  1.50     2.06      1.87   2.05   1.88

      MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0        NaN      NaN     1.92     1.95
 1       2.01     2.09     1.95     1.92
 2       2.06     1.96     1.96     1.91
 3       2.14     1.93     2.00     1.86
 4       2.08     1.99     1.98     1.88
 ..       ...      ...      ...      ...
 375     1.93     2.21     1.81     2.05
 376     2.10     1.89     2.04     1.82
 377     2.02     1.94     1.96     1.91
 378     2.05     1.99     1.96     1.91
 379     2.08     1.89     2.01     1.86

 [380 rows x 107 columns],
     Div  season        Date   Time       HomeTeam     AwayTeam  FTHG  FTAG  \
 0    E0      24  16/08/2024  20:00     Man United       Fulham     1     0
 1    E0      24  17/08/2024  12:30        Ipswich    Liverpool     0     2
 2    E0      24  17/08/2024  15:00        Arsenal       Wolves     2     0
 3    E0      24  17/08/2024  15:00        Everton     Brighton     0     3
 4    E0      24  17/08/2024  15:00      Newcastle  Southampton     1     0
 ..   ..     ...         ...    ...            ...          ...   ...   ...
 375  E0      24  25/05/2025  16:00      Newcastle      Everton     0     1
 376  E0      24  25/05/2025  16:00  Nott'm Forest      Chelsea     0     1
 377  E0      24  25/05/2025  16:00    Southampton      Arsenal     1     2
 378  E0      24  25/05/2025  16:00      Tottenham     Brighton     1     4
 379  E0      24  25/05/2025  16:00         Wolves    Brentford     1     1

     FTR  HTHG  ...  B365CAHH B365CAHA PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
 0     H     0  ...      1.86     2.07  1.83   2.11     1.88     2.11     1.82
 1     A     0  ...      2.05     1.88  2.04   1.90     2.20     2.00     1.99
 2     H     1  ...      2.02     1.91  2.00   1.90     2.05     1.93     1.99
 3     A     0  ...      1.87     2.06  1.86   2.07     1.92     2.10     1.83
 4     H     1  ...      1.87     2.06  1.88   2.06     1.89     2.10     1.82
 ..   ..   ...  ...       ...      ...   ...    ...      ...      ...      ...
 375   A     0  ...      2.00     1.85  2.01   1.90     2.01     1.95     1.95
 376   A     0  ...      1.80     2.05  1.86   2.08     1.86     2.08     1.81
 377   A     0  ...      2.03     1.83  2.04   1.87     2.07     1.87     2.03
 378   A     1  ...      1.95     1.90  2.00   1.93     2.01     1.93     1.95
 379   D     0  ...      1.85     2.00  1.90   2.03     1.90     2.05     1.85

      AvgCAHA  BFECAHH  BFECAHA
 0       2.05     1.90     2.08
 1       1.88     2.04     1.93
 2       1.87     2.02     1.96
 3       2.04     1.88     2.11
 4       2.05     1.89     2.10
 ..       ...      ...      ...
 375     1.91     1.93     2.05
 376     2.05     1.86     2.14
 377     1.83     2.06     1.89
 378     1.89     2.06     1.93
 379     1.97     1.89     2.10

 [380 rows x 121 columns],
     Div  season        Date   Time       HomeTeam        AwayTeam  FTHG  FTAG  \
 0    E2      19  03/08/2019  15:00  AFC Wimbledon       Rotherham     1     2
 1    E2      19  03/08/2019  15:00      Blackpool     Bristol Rvs     2     0
 2    E2      19  03/08/2019  15:00         Burton         Ipswich     0     1
 3    E2      19  03/08/2019  15:00       Coventry        Southend     1     0
 4    E2      19  03/08/2019  15:00      Doncaster      Gillingham     1     1
 ..   ..     ...         ...    ...            ...             ...   ...   ...
 395  E2      19  07/03/2020  15:00     Sunderland      Gillingham     2     2
 396  E2      19  10/03/2020  19:45      Blackpool        Tranmere     1     2
 397  E2      19  10/03/2020  19:45    Bristol Rvs      Sunderland     2     0
 398  E2      19  10/03/2020  19:45         Burton          Bolton     2     2
 399  E2      19  10/03/2020  19:45     Portsmouth  Fleetwood Town     2     2

     FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
 0     A     0  ...      1.72  0.25     1.88      1.98   1.84   2.06     1.95
 1     H     1  ...      1.65 -0.50     2.02      1.83   2.06   1.84     2.09
 2     A     0  ...      1.69 -0.25     1.75      2.13   1.78   2.13     1.83
 3     H     0  ...      1.81 -0.25     1.85      1.95   1.84   2.06     1.85
 4     D     1  ...      1.94 -0.50     1.93      1.93   1.96   1.94     1.97
 ..   ..   ...  ...       ...   ...      ...       ...    ...    ...      ...
 395   D     0  ...      1.60 -0.50     1.83      2.02   1.79   2.11     1.87
 396   A     0  ...      1.75 -0.75     1.98      1.88   2.00   1.90     2.04
 397   H     1  ...      1.68  0.75     1.88      1.98   1.91   1.99     1.95
 398   D     1  ...      2.08 -1.00     2.02      1.83   2.04   1.86     2.07
 399   D     1  ...      1.62 -0.25     1.75      2.05   1.77   2.15     1.83

      MaxCAHA  AvgCAHH  AvgCAHA
 0       2.04     1.88     1.96
 1       1.87     2.03     1.82
 2       2.19     1.76     2.09
 3       2.26     1.77     2.08
 4       1.96     1.92     1.91
 ..       ...      ...      ...
 395     2.11     1.79     2.04
 396     2.06     1.93     1.89
 397     2.00     1.88     1.94
 398     1.98     1.98     1.84
 399     2.16     1.76     2.09

 [400 rows x 107 columns],
     Div  season        Date   Time            HomeTeam            AwayTeam  \
 0    E2      20  12/09/2020  15:00          Accrington           Peterboro
 1    E2      20  12/09/2020  15:00               Crewe            Charlton
 2    E2      20  12/09/2020  15:00           Doncaster  Milton Keynes Dons
 3    E2      20  12/09/2020  15:00      Fleetwood Town              Burton
 4    E2      20  12/09/2020  15:00          Gillingham                Hull
 ..   ..     ...         ...    ...                 ...                 ...
 547  E2      20  09/05/2021  12:00  Milton Keynes Dons            Rochdale
 548  E2      20  09/05/2021  12:00              Oxford              Burton
 549  E2      20  09/05/2021  12:00          Portsmouth          Accrington
 550  E2      20  09/05/2021  12:00          Sunderland         Northampton
 551  E2      20  09/05/2021  12:00               Wigan             Swindon

      FTHG  FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  \
 0       2     0   H     1  ...      2.03  0.25     2.02      1.83   2.08
 1       0     2   A     0  ...      1.88  0.00     1.95      1.90   1.96
 2       1     1   D     0  ...      1.69 -0.25     1.80      2.05   1.81
 3       2     1   H     1  ...      1.85 -0.50     1.98      1.88   1.95
 4       0     2   A     0  ...      1.86  0.00     1.85      2.00   1.91
 ..    ...   ...  ..   ...  ...       ...   ...      ...       ...    ...
 547     0     3   A     0  ...      2.56 -0.75     1.88      1.98   1.88
 548     4     0   H     2  ...      2.38 -1.00     1.85      2.00   1.88
 549     0     1   A     0  ...      2.21 -1.00     1.95      1.90   1.99
 550     1     1   D     0  ...      2.13 -1.25     1.98      1.88   2.02
 551     3     4   A     1  ...      2.28 -0.75     1.93      1.93   2.00

      PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
 0     1.83     2.09     1.87     2.02     1.81
 1     1.94     2.00     1.95     1.94     1.89
 2     2.12     1.85     2.12     1.80     2.05
 3     1.95     2.06     1.95     1.97     1.86
 4     2.00     1.93     2.06     1.85     1.99
 ..     ...      ...      ...      ...      ...
 547   2.01     1.96     2.04     1.87     1.97
 548   2.02     2.11     2.06     1.88     1.95
 549   1.90     2.07     1.94     1.95     1.88
 550   1.88     2.10     1.91     2.01     1.83
 551   1.88     2.01     1.97     1.93     1.90

 [552 rows x 107 columns],
     Div  season        Date   Time        HomeTeam            AwayTeam  FTHG  \
 0    E2      21  07/08/2021  15:00          Bolton  Milton Keynes Dons     3
 1    E2      21  07/08/2021  15:00       Cambridge              Oxford     1
 2    E2      21  07/08/2021  15:00           Crewe          Cheltenham     1
 3    E2      21  07/08/2021  15:00       Doncaster       AFC Wimbledon     1
 4    E2      21  07/08/2021  15:00  Fleetwood Town          Portsmouth     0
 ..   ..     ...         ...    ...             ...                 ...   ...
 547  E2      21  30/04/2022  12:30       Morecambe          Sunderland     0
 548  E2      21  30/04/2022  12:30          Oxford           Doncaster     1
 549  E2      21  30/04/2022  12:30        Plymouth  Milton Keynes Dons     0
 550  E2      21  30/04/2022  12:30  Sheffield Weds          Portsmouth     4
 551  E2      21  30/04/2022  12:30      Shrewsbury               Wigan     0

      FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
 0       3   D     1  ...      1.97 -0.25     1.90      1.95   1.91   1.97
 1       1   D     0  ...      1.86  0.25     2.08      1.73   2.12   1.78
 2       1   D     1  ...      1.69 -0.25     2.00      1.85   1.99   1.90
 3       2   A     0  ...      1.88 -0.25     2.10      1.77   2.11   1.80

In [22]:
# total frames (6 seasons times 3 leagues)
len(frames)

18

In [ ]:
# show first and last element (new season column was created)
frames[0]

# Organise all the data in a dictionary

In [24]:
# create a dictionary with the original name of league as key
dict_countries = {'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
                  'German Bundesliga 1':'D1',
                  'English Premier League':'E0', 'English League 1':'E1', 'English League 2':'E2'}

In [26]:
# get a dictionary element
dict_countries['English Premier League']

'E0'

In [28]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E1
E2

In [33]:
dict_historical_data = {}

# creating list of leagues
# leagues = ['E0', 'E2', 'E3']

# looping through key elements
for league in dict_countries:
    frames = []
    for season in range(19, 25):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)
        df_concat = pd.concat(frames)
        dict_historical_data[league] = df_concat

# show dataframe inside dict_historical_data
dict_historical_data.keys()